version: '2.4'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    container_name: elasticsearch
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - discovery.type=single-node
      - bootstrap.system_call_filter=false

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.1
    environment:
       ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 127.0.0.1:5601:5601
